//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.DataLayer.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EfContext : DbContext
    {
        public EfContext()
            : base("name=EfContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CostOrIncome> CostOrIncomes { get; set; }
        public virtual DbSet<CostOrIncomeType> CostOrIncomeTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
