//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.DataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostOrIncome
    {
        public long Id { get; set; }
        public long CostOrIncomeTypeId { get; set; }
        public long UserId { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; }
        public byte Type { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public bool IsRemoved { get; set; }
    
        public virtual CostOrIncomeType CostOrIncomeType { get; set; }
        public virtual User User { get; set; }
    }
}
